- name: create vmware virtual machine
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "{{ vm_folder }}"
    name: "{{ vm_name }}"
    state: "{{ vm_state }}"
    template: "{{ vm_template }}"
    wait_for_ip_address: true
